### ISSUE TITLE
Add a "Delete Tag" button

### ISSUE THREAD

**Issue by dv297** [codeforkansascity/tagging-tracker#10]
As a member of the Graffiti Abatement Tracking Program
I want an icon to delete tags
so that erroneous or redundant tags can be removed.

We will know when we are done when
* on iOS
  * you can swipe left on the tag list to delete an item
* on Android
  * you can hold the list item which will bring a new menu to delete the item

**Comment by JakeLaCombe** [comment]
I think a table view can assist here. https://github.com/aksonov/react-native-tableview#features

**Comment by JakeLaCombe** [comment]
Android Designs can be found here.

<img width="571" alt="screen shot 2017-10-05 at 10 48 04 pm" src="https://user-images.githubusercontent.com/2552573/31262229-4ce5faca-aa1f-11e7-8088-1962c019f24e.png">

**Comment by JakeLaCombe** [comment]
Note the use of the trash can icon for deleting the tags.

**Comment by JakeLaCombe** [comment]
For iOS, let's use both sliders and delete buttons.

<img width="550" alt="screen shot 2017-10-12 at 8 41 38 pm" src="https://user-images.githubusercontent.com/2552573/31526658-dbb63ea4-af8d-11e7-94a4-212038d95654.png">
