### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/tagging-tracker#20]
![20170710_100222](https://user-images.githubusercontent.com/22461039/40949019-7ab092a0-6831-11e8-844a-5ede00fc415f.jpg)
![20170710_102355](https://user-images.githubusercontent.com/22461039/40949020-7ac3430a-6831-11e8-8729-e38d5a4bf78c.jpg)
![20170710_103654](https://user-images.githubusercontent.com/22461039/40949021-7ad35d26-6831-11e8-8317-8f26eecf51d9.jpg)
![dsc03132](https://user-images.githubusercontent.com/22461039/40949022-7ae30758-6831-11e8-84e3-d6c8b6db45da.jpg)
![dsc03140](https://user-images.githubusercontent.com/22461039/40949023-7af5b72c-6831-11e8-9e3b-f874cade5843.jpg)
![dsc03194](https://user-images.githubusercontent.com/22461039/40949024-7b075b9e-6831-11e8-9ff8-38e2a296c851.jpg)

**Comment by AmandaWilsonKC** [comment]
![20170710_100222 small](https://user-images.githubusercontent.com/22461039/41262100-968156ea-6da4-11e8-9f9b-e6a5b3790137.jpeg)
![20170710_103654 small](https://user-images.githubusercontent.com/22461039/41262101-968f2c16-6da4-11e8-8d5c-fe9b730a1e13.jpeg)
![dsc03132 small](https://user-images.githubusercontent.com/22461039/41262102-969b7020-6da4-11e8-85d2-9ea8dcce2c92.jpeg)
![dsc03194 small](https://user-images.githubusercontent.com/22461039/41262103-96a9df2a-6da4-11e8-9308-c2cd6cd669ac.jpeg)

**Comment by AmandaWilsonKC** [comment]
![1](https://user-images.githubusercontent.com/22461039/41263286-86d6d916-6dab-11e8-9570-2617297ea2e0.jpg)

**Comment by kolkheang** [comment]
Photos were added to the README with this PR https://github.com/codeforkansascity/tagging-tracker/pull/23.
