### ISSUE TITLE
Add thumbnail to Tag List

### ISSUE THREAD

**Issue by dv297** [codeforkansascity/tagging-tracker#7]
As a member of the Graffiti Abatement Tracking Program
I want a thumbnail of the tag to be visible next to the tag entry
so that I can easily access and remember what entry goes to which tag.

We know when we are done when
* we can see a thumbnail of each tag in the Tag List.

**Comment by JakeLaCombe** [comment]
Android Design can be found here. 
<img width="393" alt="screen shot 2017-10-05 at 10 49 19 pm" src="https://user-images.githubusercontent.com/2552573/31262252-76d750b8-aa1f-11e7-848d-bf27e406e6e7.png">

**Comment by JakeLaCombe** [comment]
Resolved in https://github.com/codeforkansascity/tagging-tracker/pull/14
